//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public System.Guid Team1 { get; set; }
        public System.Guid Team2 { get; set; }
        public byte Result { get; set; }
        public Nullable<byte> Team1BidPercent { get; set; }
        public Nullable<byte> Team2BidPercent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> League { get; set; }
        public bool IsFinished { get; set; }
    
        public virtual League League1 { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team3 { get; set; }
    }
}
