//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Games = new HashSet<Game>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string PictureUrl { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
